server:
  port: 8080

spring:
  application:
    name: merchantplatform

datasource:
  url: jdbc:postgresql://localhost:5432/merchantplatform
  username: postgres
  password: Jurgy00
  driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
mpesa:
    consumer-key: ${MPESA_CONSUMER_KEY}
    consumer-secret: ${MPESA_CONSUMER_SECRET}
    short-code: 174379
    passkey: "bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919"
    callback-url: "https://stratus-tabby-satisfied.ngrok-free.dev/api/payments/mpesa/callback"
    auth-url: "https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials"
    stk-push-url: "https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest"
